// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */
var MiyoFilters;

if (typeof MiyoFilters === "undefined" || MiyoFilters === null) {
  MiyoFilters = {};
}

MiyoFilters.raw = {
  type: 'data-value',
  filter: function(argument, request, id, stash) {
    if ((argument != null ? argument.raw : void 0) == null) {
      throw 'argument.raw undefined';
    }
    return argument.raw;
  }
};

if ((typeof module !== "undefined" && module !== null) && (module.exports != null)) {
  module.exports = MiyoFilters;
}

//# sourceMappingURL=raw.js.map
